# Generated by Django 4.0 on 2022-09-07 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectFencers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_accepts', models.BooleanField(default=False)),
                ('c_accepts', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='authentication.user')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='authentication.user')),
            ],
        ),
    ]
