from django.db import models

class USAFencingInfo(models.Model):
    member_id = models.IntegerField(unique=True)
    last_name = models.CharField(max_length=100, null = True, blank=True)
    first_name = models.CharField(max_length=100, null = True, blank=True)
    middle_name = models.CharField(max_length=100, null = True, blank=True)
    suffix = models.CharField(max_length=10, null = True, blank=True)
    nickname = models.CharField(max_length=100, null = True, blank=True)
    gender = models.CharField(max_length=10, null = True, blank=True)
    birthdate = models.IntegerField(null = True, blank=True)
    birthdate_verified = models.BooleanField(default=False)
    division= models.CharField(max_length=100, null = True, blank=True)
    club1 = models.CharField(max_length=100, null = True, blank=True)
    club1_abv = models.CharField(max_length=100, null = True, blank=True)
    club1_id = models.IntegerField(null = True, blank=True)
    club2 = models.CharField(max_length=100, null = True, blank=True)
    club2_abv = models.CharField(max_length=100, null = True, blank=True)
    club2_id = models.IntegerField(null = True, blank=True)
    school = models.CharField(max_length=100, null = True, blank=True)
    school_abv = models.CharField(max_length=100, null = True, blank=True)
    school_id = models.IntegerField(null = True, blank=True)
    member_type = models.CharField(max_length=100, null = True, blank=True)
    checked = models.BooleanField(default=False)
    competitive = models.BooleanField(default=False)
    expiration = models.DateField(null = True, blank=True)
    sabre = models.CharField(max_length=7, null = True, blank=True)
    epee = models.CharField(max_length=7, null = True, blank=True)
    foil = models.CharField(max_length=7, null = True, blank=True)
    us_citizen = models.BooleanField(default=False)
    permanent = models.BooleanField(default=False)
    country = models.CharField(max_length=100, null = True, blank=True)
    region = models.IntegerField(null = True, blank=True)
    background_expires = models.DateField(null = True, blank=True)
    safesport_expires = models.DateField(null = True, blank=True)
    non_competitive = models.BooleanField(null = True, blank=True)
    highest_ref_rating = models.CharField(max_length=5, null = True, blank=True)
    us_ref_foil = models.CharField(max_length=5, null = True, blank=True)
    us_ref_foil_year = models.IntegerField(null = True, blank=True)
    us_ref_epee = models.CharField(max_length=5, null = True, blank=True)
    us_ref_epee_year = models.IntegerField(null = True, blank=True)
    us_ref_sabre = models.CharField(max_length=5, null = True, blank=True)
    us_ref_sabre_year = models.IntegerField(null = True, blank=True)
    fie_ref_foil = models.CharField(max_length=5, null = True, blank=True)
    fie_ref_foil_year = models.IntegerField(null = True, blank=True)
    fie_ref_epee = models.CharField(max_length=5, null = True, blank=True)
    fie_ref_epee_year = models.IntegerField(null = True, blank=True)
    fie_ref_sabre = models.CharField(max_length=5, null = True, blank=True)
    fie_ref_sabre_year = models.IntegerField(null = True, blank=True)
    #missing date time fields for updated and modified